# Generated by Django 3.2.9 on 2021-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default='21-11-11'),
        ),
    ]
