# Generated by Django 3.2.9 on 2021-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_student_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_joined',
            field=models.DateField(default='2021-11-11'),
        ),
    ]
