# Generated by Django 3.2.9 on 2021-11-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_student_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_joined',
        ),
    ]
